language: ruby
cache: bundler

rvm:
  - 2.2.0

cache:
  - bundler
  - apt

addons:
  code_climate:
    repo_token:
      secure: 'kuBlU99XkssFqCzqc1Fi1xJPV2yr8D2/emtlsq+637aXhIw+COBgunW2/pVY3JeTVfEQZGb37dJ/2W/Vg8za5L1uHYXHGcoEIAxjVtMFzGADCH6alSSLN0WxMJBjZh/znmbcbq4C+uDrI37VkQTNbukeyW4zVLyxj3agwK5CwLI='

env:
  - SECRET_KEY_BASE=9cfeda93735dbaa1ef60eefbad96d6c01916a24c6dff07a623362db7c47e39cffeccb7702ff0b6d19ede7d7e8d8a50fde43c47c1771490ab03f5d046873f6c6c
  - secure: 'hnpajNizVIEQOXQ7Yf+LO+deK2TGf4jE7lkQDLxx24aVqMzvbsbFQ+GMkrXoPPPNvgU7gnCrdoKQTBn4bj+uH4Sp+Bg0xFA9TNFriNcIZE1Ja4JZZW0GN9MfgaEd0gP4AQxR8IQMqtH/Rl01NpuUwdcBwSsfVnjqQe5HH/CkEE4='
  - GITHUB_APP_KEY='enter a real github app key here'
  - GITHUB_APP_SECRET='enter a real github app secret here'
