# By default, configure application secrets and other sensitive data via
# configurations defined within the application's environment variables.
#
# Developers may override environment variables by setting keys manually
# within this file. Note that this file is ignored by git by default,
# so you'll need to `git add --force config/secrets.yml` to persist any updates
# to this file.
#
# Finally, please note that we use `ENV.fetch` to retreive configuration values
# that are rquired for the application to run. Doing so prevents this
# application from starting if it is missing data required for it's operation.
defaults: &defaults
  secret_key_base: <%= ENV.fetch('SECRET_KEY_BASE') %>
  authy_api_key: <%= ENV.fetch('AUTHY_API_KEY') %>
  github_app_id: <%= ENV.fetch('GITHUB_APP_KEY') %>
  github_app_secret: <%= ENV.fetch('GITHUB_APP_SECRET') %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
